# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

inhibit_all_warnings!

target 'KotlinMultiplatformApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for KotlinMultiplatformApp
  pod 'Firebase/Core'
  pod 'Firebase/Firestore'
  pod 'Himotoki'

  target 'KotlinMultiplatformAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
